### ISSUE TITLE
Bug: Visual bug when loading apis list

### ISSUE THREAD

**Issue by kbuczynski-nashpl** [faraazahmad/apiland#1]
Hi I notice when i am scrolled to the bototm of the screen while visiting a `https://faraazahmad.github.io/apiland/#/` 
and then clicking `Explore API's` a page `https://faraazahmad.github.io/apiland/#/explore` loads but I am at the bottom of the screen instead being on top 🤔 

Browser Chrome (Version 85)
OS Windows10

**Comment by faraazahmad** [comment]
Yeah that is an issue right now. I'm looking into how to fix it

**Comment by faraazahmad** [comment]
Solved by @suyashchauhan
