### ISSUE TITLE
No left margin in mobile

### ISSUE THREAD

**Issue by ghost** [faraazahmad/apiland#5]
![Screenshot_2020-09-02-09-07-40-482_com android chrome](https://user-images.githubusercontent.com/59839368/91929437-ff285080-ecfb-11ea-8273-c0cd840fee92.jpg)

**Comment by faraazahmad** [comment]
Thanks for opening issue its being worked on in #6

**Comment by troyfitzwater** [comment]
Hey there! I was wondering if you were still looking for help on this? I noticed that there was an open PR for it, but it hasn't been updated for a few weeks. I think I just got a fix for it working locally, so would I be able to open my own PR for it?

Edit: I should clarify that the fix I have also addresses the issue that PR #6  has with the width on the left and right of each card not being equal.

**Comment by faraazahmad** [comment]
Awesome @troyfitzwater ! Yeah we still need help on this issue. You can open your own PR. Make sure to include a screenshot
